---
name: Linter

on:
    pull_request:
        branches: [main]

jobs:
    build:
        name: Run Linters
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install dependencies
              run: npm install

            - name: Lint
              uses: github/super-linter@v3
              env:
                  CSS_FILE_NAME: .stylelintrc.yml
                  DEFAULT_BRANCH: main
                  FILTER_REGEX_EXCLUDE: .*node_modules.*
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LINTER_RULES_PATH: ./
                  VALIDATE_JAVASCRIPT_STANDARD: false

            - name: Debugging
              run: |
                pwd
                echo running ls
                ls
                echo running ls dist
                ls dist
                echo running ls dist/assets
                ls dist/assets
